# Global configuration
destination: ../dist
lang: fr_FR
environment: "development"

# Site settings
title: Synapsium - Startup studio
author: Nicolas Law-dune
email: contact@synapsium.com
keywords: synapsium
description: Le collectif de freelance seniors, passionnés et spécialistes des nouvelles technologies et du digital.
baseurl: ""
url: "https://synapsium.com"
twitter:
  username: synapsium
  card: summary
  creator: nlawdune

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - scss
  - scripts
  - node_modules
  - README.md
  - gulpfile.js
  - package-lock.json
  - package.json
