# Global configuration
destination: ../dist
lang: fr_FR
environment: "production"

# Site settings
title: Synapsium - Accélérateur Digital & Product Factory
author: Nicolas Law-dune
email: contact@synapsium.com
keywords: freelance,consultant,digital,transformation,developpement,data,startup,innovation,business,marketing,produit,application,stratégie
description: Nous sommes un cabinet indépendant de conseil en transformation numérique, nous vous accompagnons dans vos projets de transformation et d’innovation sur le digital.
baseurl: ""
url: "https://synapsium.com"
twitter:
  username: synapsium
  card: summary
  creator: nlawdune

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - scss
  - scripts
  - node_modules
  - README.md
  - gulpfile.js
  - package-lock.json
  - package.json
